@startuml
class 投稿{
	-投稿ID
	-ユーザID
	-内容
	-日付
}
class ユーザ{
	-ユーザ名
	-ユーザID
	-パスワード
	+削除()
	+投稿()
}

class 投稿リポジトリ{
	+全検索()
	+検索(投稿ID)
	+書き込み(投稿)
	+削除(投稿ID)
}
class ユーザリポジトリ{
	+ログイン(ユーザ名,パスワード)
	+検索(ユーザID)
}
class BBSコントローラ{
	+表示()
	+書き込み確認()
	+書き込み()
	+ログイン()
	+ログアウト()
	+削除確認()
	+削除()
}
ユーザ -o 投稿
ユーザ --o ユーザリポジトリ
投稿 --o 投稿リポジトリ
BBSコントローラ --> 投稿リポジトリ
BBSコントローラ --> ユーザリポジトリ
@enduml
