@startuml
title 画面遷移
ログイン:トップ自動遷移
ログアウト:トップ自動遷移
書き込み:トップ自動遷移
削除:トップ自動遷移

[*]->掲示板トップ
掲示板トップ-->ログイン
掲示板トップ-->ログアウト
掲示板トップ-->書き込み確認:書き込みボタン
書き込み確認-->書き込み:実行ボタン
掲示板トップ-->削除確認:削除ボタン
削除確認-->削除:削除ボタン
@enduml
